image: php:7.4-apache

stages:
  - build
  - FunctionsTest

build:
  stage: build
  script:
    - apt-get update -yqq
    - apt-get install -yqq git unzip
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install
  artifacts:
    paths:
      - vendor/

FunctionsTest:
  stage: FunctionsTest
  script:
    - vendor/bin/phpunit --bootstrap vendor/autoload.php src/FunctionsTest.php